/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextRouteImport } from './routes/text'
import { Route as NewRouteImport } from './routes/new'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextIdRouteImport } from './routes/text.$id'
import { Route as PIdRouteImport } from './routes/p.$id'

const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextIdRoute = TextIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TextRoute,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/new': typeof NewRoute
  '/text': typeof TextRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/text/$id': typeof TextIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/new': typeof NewRoute
  '/text': typeof TextRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/text/$id': typeof TextIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/new': typeof NewRoute
  '/text': typeof TextRouteWithChildren
  '/p/$id': typeof PIdRoute
  '/text/$id': typeof TextIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/health' | '/new' | '/text' | '/p/$id' | '/text/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/health' | '/new' | '/text' | '/p/$id' | '/text/$id'
  id: '__root__' | '/' | '/health' | '/new' | '/text' | '/p/$id' | '/text/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  NewRoute: typeof NewRoute
  TextRoute: typeof TextRouteWithChildren
  PIdRoute: typeof PIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text/$id': {
      id: '/text/$id'
      path: '/$id'
      fullPath: '/text/$id'
      preLoaderRoute: typeof TextIdRouteImport
      parentRoute: typeof TextRoute
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TextRouteChildren {
  TextIdRoute: typeof TextIdRoute
}

const TextRouteChildren: TextRouteChildren = {
  TextIdRoute: TextIdRoute,
}

const TextRouteWithChildren = TextRoute._addFileChildren(TextRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  NewRoute: NewRoute,
  TextRoute: TextRouteWithChildren,
  PIdRoute: PIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
